In [2]:
from pyhive import hive

In [3]:
conn = hive.Connection(
    host="localhost",  # Your Hive server's host
    port=10000,        # Your Hive server's port
    username="hive",   # Your Hive username
    database="default" # Optional: specify your Hive database
)

In [4]:
# Create a cursor object
cursor = conn.cursor()

# Execute the query with a LIMIT clause
cursor.execute("SELECT * FROM fraude LIMIT 5")

# Fetch and print the results
for row in cursor.fetchall():
    print(row)

(516733, '2020-12-22 20:30:27', 503874407318, 'fraud_Parker-Kunde', 'personal_care', 1.8, 'Andrew', 'Mcgee', 'M', '4130 Tiffany Glen Apt. 562', 'San Antonio', 'TX', 78248, 29.5894, -98.5201, 1595797, 'Exhibition designer', '1975-12-28', 'd9ce24d0402de602f672aad6846341ba', 1387744227, 29.760897, -97.711639, 0)
(455518, '2019-07-21 04:02:54', 675909898057, 'fraud_Kiehn Inc', 'grocery_pos', 114.66, 'Christopher', 'Henry', 'M', '1198 Robert Stravenue Apt. 479', 'Armonk', 'NY', 10504, 41.136, -73.7009, 7987, 'Television/film/video producer', '1964-03-16', 'f79fb23187ac2e2a5340bc2bd6977b0e', 1342843374, 40.181098, -74.074658, 0)
(24653, '2019-01-15 06:58:17', 343819048608995, 'fraud_Kerluke Inc', 'misc_net', 5.66, 'Shelby', 'Cannon', 'F', '1535 Ryan Burgs Suite 919', 'Des Moines', 'IA', 50312, 41.5855, -93.6719, 222785, 'Wellsite geologist', '1956-01-24', 'f7a8019bf073a0d0d3fe989964f69e4e', 1326610697, 41.872861, -93.593975, 0)
(538193, '2019-08-18 22:56:31', 2348245054386329, 'fraud_Lubowitz Terry and Stracke', 'personal_care', 20.22, 'Justin', 'Gay', 'M', '268 Hayes Rue Suite 811', 'Harborcreek', 'PA', 16421, 42.1767, -79.9416, 2518, 'Event organiser', '1946-02-02', 'af21daf61caede2be22a8281914935a5', 1345330591, 42.280778000000005, -79.16318100000001, 0)
(1173680, '2020-05-04 22:14:17', 30197398657930, 'fraud_Pfeffer and Sons', 'shopping_pos', 45.08, 'April', 'Johnson', 'F', '9727 Deleon Mountain', 'Creedmoor', 'NC', 27522, 36.1124, -78.6476, 12335, 'Chief Strategy Officer', '1987-09-19', 'a4f11566e429463808a01f1c5738eb85', 1367705657, 35.959581, -78.434569, 0)

In [15]:
# Create a cursor object
cursor = conn.cursor()

# Execute the query
cursor.execute("SELECT DISTINCT is_fraud FROM fraude ORDER BY is_fraud")

# Fetch and print the results
for row in cursor.fetchall():
    print(row)

(0,)
(1,)

In [13]:
# Création d'un curseur
cursor = conn.cursor()

# Exécuter une requête sur la table
cursor.execute("SELECT * FROM fraude LIMIT 1")

# Obtenir les noms des colonnes
column_names = [desc[0] for desc in cursor.description]

# Afficher les noms des colonnes
print("Noms des colonnes :", column_names)

# Fermer le curseur et la connexion
cursor.close()

Noms des colonnes : ['fraude.unnamed_0', 'fraude.trans_date_trans_time', 'fraude.cc_num', 'fraude.merchant', 'fraude.category', 'fraude.amt', 'fraude.first', 'fraude.last', 'fraude.gender', 'fraude.street', 'fraude.city', 'fraude.state', 'fraude.zip', 'fraude.lat', 'fraude.long', 'fraude.city_pop', 'fraude.dob', 'fraude.trans_num', 'fraude.unix_time', 'fraude.merch_lat', 'fraude.merch_long', 'fraude.is_fraud']

In [17]:
# Création d'un curseur
cursor = conn.cursor()

# Requête pour obtenir les valeurs uniques de la colonne is_fraud
cursor.execute("SELECT DISTINCT is_fraud FROM transactions")

# Récupérer et afficher les résultats
unique_values = [row[0] for row in cursor.fetchall()]
print("Valeurs uniques de 'is_fraud' :", unique_values)

Valeurs uniques de 'is_fraud' : [0, 1]

In [18]:
# Create a cursor object
cursor = conn.cursor()

# Execute the query to fetch distinct job values
cursor.execute("SELECT DISTINCT job FROM transactions ORDER BY job")

# Fetch and print the results
for row in cursor.fetchall():
    print(row[0])  # row[0] car 'job' est la première colonne dans la requête

Academic librarian
Accountant_chartered
Accountant_chartered certified
Accountant_chartered public finance
Accounting technician
Acupuncturist
Administrator
Administrator_arts
Administrator_charities/voluntary organisations
Administrator_education
Administrator_local government
Advertising account executive
Advertising account planner
Advertising copywriter
Advice worker
Aeronautical engineer
Agricultural consultant
Aid worker
Air broker
Air cabin crew
Air traffic controller
Airline pilot
Ambulance person
Amenity horticulturist
Analytical chemist
Animal nutritionist
Animal technologist
Animator
Applications developer
Arboriculturist
Archaeologist
Architect
Architectural technologist
Archivist
Armed forces logistics/support/administrative officer
Armed forces technical officer
Armed forces training and education officer
Art gallery manager
Art therapist
Artist
Arts development officer
Associate Professor
Audiological scientist
Barista
Barrister
Barrister's clerk
Biochemist_clinical
Biomedical engineer
Biomedical scientist
Bookseller
Broadcast engineer
Broadcast journalist
Broadcast presenter
Building control surveyor
Building services engineer
Building surveyor
Buyer_industrial
Buyer_retail
Cabin crew
Call centre manager
Camera operator
Careers adviser
Careers information officer
Cartographer
Catering manager
Ceramics designer
Charity fundraiser
Charity officer
Chartered accountant
Chartered legal executive (England and Wales)
Chartered loss adjuster
Chartered public finance accountant
Chemical engineer
Chemist_analytical
Chief Executive Officer
Chief Financial Officer
Chief Marketing Officer
Chief Operating Officer
Chief Strategy Officer
Chief Technology Officer
Chief of Staff
Child psychotherapist
Chiropodist
Civil Service administrator
Civil Service fast streamer
Civil engineer_contracting
Claims inspector/assessor
Clinical biochemist
Clinical cytogeneticist
Clinical psychologist
Clinical research associate
Clothing/textile technologist
Colour technologist
Commercial horticulturist
Commercial/residential surveyor
Commissioning editor
Communications engineer
Community arts worker
Community development worker
Community education officer
Community pharmacist
Company secretary
Comptroller
Conservation officer_historic buildings
Conservator_furniture
Conservator_museum/gallery
Contracting civil engineer
Contractor
Control and instrumentation engineer
Copy
Copywriter_advertising
Corporate investment banker
Counselling psychologist
Counsellor
Curator
Cytogeneticist
Dance movement psychotherapist
Dancer
Data scientist
Database administrator
Dealer
Designer_ceramics/pottery
Designer_exhibition/display
Designer_furniture
Designer_industrial/product
Designer_interior/spatial
Designer_jewellery
Designer_multimedia
Designer_television/film set
Designer_textile
Development worker_community
Development worker_international aid
Diagnostic radiographer
Dispensing optician
Doctor_general practice
Doctor_hospital
Drilling engineer
Early years teacher
Ecologist
Economist
Editor_commissioning
Editor_film/video
Editor_magazine features
Education administrator
Education officer_community
Education officer_museum
Educational psychologist
Electrical engineer
Electronics engineer
Embryologist_clinical
Emergency planning/management officer
Energy engineer
Energy manager
Engineer_aeronautical
Engineer_agricultural
Engineer_automotive
Engineer_biomedical
Engineer_broadcasting (operations)
Engineer_building services
Engineer_civil (consulting)
Engineer_civil (contracting)
Engineer_communications
Engineer_control and instrumentation
Engineer_drilling
Engineer_electronics
Engineer_land
Engineer_maintenance
Engineer_manufacturing
Engineer_materials
Engineer_mining
Engineer_petroleum
Engineer_production
Engineer_site
Engineer_structural
Engineer_technical sales
Engineer_water
Engineering geologist
English as a foreign language teacher
English as a second language teacher
Environmental consultant
Environmental education officer
Environmental health practitioner
Environmental manager
Equality and diversity officer
Equities trader
Estate manager/land agent
Event organiser
Exercise physiologist
Exhibition designer
Exhibitions officer_museum/gallery
Facilities manager
Farm manager
Field seismologist
Field trials officer
Film/video editor
Financial adviser
Financial trader
Fine artist
Firefighter
Fisheries officer
Fitness centre manager
Forensic psychologist
Forest/woodland manager
Freight forwarder
Furniture conservator/restorer
Furniture designer
Further education lecturer
Futures trader
Gaffer
Garment/textile technologist
General practice doctor
Geneticist_molecular
Geochemist
Geologist_engineering
Geologist_wellsite
Geophysicist/field seismologist
Geoscientist
Glass blower/designer
Health and safety adviser
Health physicist
Health promotion specialist
Health service manager
Health visitor
Herbalist
Heritage manager
Herpetologist
Higher education careers adviser
Historic buildings inspector/conservation officer
Homeopath
Horticultural consultant
Horticultural therapist
Horticulturist_commercial
Hospital doctor
Hospital pharmacist
Hotel manager
Human resources officer
Hydrogeologist
Hydrographic surveyor
Hydrologist
IT consultant
IT trainer
Illustrator
Immigration officer
Immunologist
Industrial buyer
Industrial/product designer
Information officer
Information systems manager
Insurance broker
Insurance claims handler
Insurance risk surveyor
Insurance underwriter
Intelligence analyst
Interior and spatial designer
Interpreter
Investment analyst
Investment banker_corporate
Investment banker_operational
Jewellery designer
Journalist_newspaper
Land
Land/geomatics surveyor
Landscape architect
Lawyer
Learning disability nurse
Learning mentor
Lecturer_further education
Lecturer_higher education
Legal secretary
Leisure centre manager
Lexicographer
Librarian_academic
Librarian_public
Licensed conveyancer
Local government officer
Location manager
Logistics and distribution manager
Loss adjuster_chartered
Magazine features editor
Magazine journalist
Maintenance engineer
Make
Management consultant
Manufacturing engineer
Manufacturing systems engineer
Market researcher
Marketing executive
Materials engineer
Mechanical engineer
Media buyer
Media planner
Medical physicist
Medical sales representative
Medical secretary
Medical technical officer
Mental health nurse
Merchandiser_retail
Metallurgist
Minerals surveyor
Mining engineer
Mudlogger
Multimedia programmer
Museum education officer
Museum/gallery conservator
Museum/gallery exhibitions officer
Music therapist
Music tutor
Musician
Nature conservation officer
Naval architect
Network engineer
Neurosurgeon
Nurse_children's
Nurse_mental health
Nutritional therapist
Occupational hygienist
Occupational psychologist
Occupational therapist
Oceanographer
Oncologist
Operational investment banker
Operational researcher
Operations geologist
Optician_dispensing
Optometrist
Orthoptist
Osteopath
Outdoor activities/education manager
Paediatric nurse
Paramedic
Patent attorney
Pathologist
Pension scheme manager
Pensions consultant
Personnel officer
Petroleum engineer
Pharmacist_community
Pharmacist_hospital
Pharmacologist
Physicist_medical
Physiological scientist
Physiotherapist
Phytotherapist
Pilot_airline
Planning and development surveyor
Plant breeder/geneticist
Podiatrist
Police officer
Politician's assistant
Presenter_broadcasting
Press photographer
Press sub
Primary school teacher
Prison officer
Private music teacher
Probation officer
Producer_radio
Producer_television/film/video
Product designer
Product manager
Product/process development scientist
Production assistant_radio
Production assistant_television
Production engineer
Production manager
Professor Emeritus
Programme researcher_broadcasting/film/video
Programmer_applications
Programmer_multimedia
Psychiatric nurse
Psychiatrist
Psychologist_clinical
Psychologist_counselling
Psychologist_forensic
Psychologist_sport and exercise
Psychotherapist
Psychotherapist_child
Public affairs consultant
Public house manager
Public librarian
Public relations account executive
Public relations officer
Purchasing manager
Quantity surveyor
Quarry manager
Race relations officer
Radio broadcast assistant
Radio producer
Radiographer_diagnostic
Radiographer_therapeutic
Records manager
Regulatory affairs officer
Research officer_political party
Research officer_trade union
Research scientist (life sciences)
Research scientist (maths)
Research scientist (medical)
Research scientist (physical sciences)
Restaurant manager_fast food
Retail banker
Retail buyer
Retail manager
Retail merchandiser
Risk analyst
Rural practice surveyor
Sales executive
Sales professional_IT
Sales promotion account executive
Science writer
Scientific laboratory technician
Scientist_audiological
Scientist_biomedical
Scientist_clinical (histocompatibility and immunogenetics)
Scientist_marine
Scientist_physiological
Scientist_research (maths)
Scientist_research (medical)
Scientist_research (physical sciences)
Secondary school teacher
Secretary/administrator
Seismic interpreter
Senior tax professional/tax inspector
Set designer
Ship broker
Site engineer
Social research officer_government
Social researcher
Software engineer
Soil scientist
Solicitor
Solicitor_Scotland
Special educational needs teacher
Special effects artist
Sport and exercise psychologist
Sports administrator
Sports development officer
Stage manager
Statistician
Structural engineer
Sub
Surgeon
Surveyor_hydrographic
Surveyor_land/geomatics
Surveyor_minerals
Surveyor_mining
Surveyor_rural practice
Systems analyst
Systems developer
TEFL teacher
Tax adviser
Tax inspector
Teacher_English as a foreign language
Teacher_adult education
Teacher_early years/pre
Teacher_primary school
Teacher_secondary school
Teacher_special educational needs
Teaching laboratory technician
Technical brewer
Telecommunications researcher
Television camera operator
Television floor manager
Television production assistant
Television/film/video producer
Textile designer
Theatre director
Theatre manager
Theme park manager
Therapist_art
Therapist_drama
Therapist_horticultural
Therapist_music
Therapist_occupational
Therapist_sports
Tour manager
Tourism officer
Tourist information centre manager
Town planner
Toxicologist
Trade mark attorney
Trading standards officer
Training and development officer
Transport planner
Travel agency manager
Tree surgeon
Veterinary surgeon
Video editor
Visual merchandiser
Volunteer coordinator
Warden/ranger
Warehouse manager
Waste management officer
Water engineer
Water quality scientist
Web designer
Wellsite geologist
Writer

In [19]:
# Create a cursor object
cursor = conn.cursor()

# Execute the query to count the number of rows in the transactions table
cursor.execute("SELECT COUNT(*) FROM transactions")

# Fetch the result
row_count = cursor.fetchone()[0]  # `fetchone()` renvoie un tuple, on récupère la première valeur

# Print the number of rows
print(f"Nombre de lignes dans la table transactions : {row_count}")

Nombre de lignes dans la table transactions : 1852394

In [1]:
import pandas as pd

In [7]:
bd =pd.read_csv("/home/master/csv_batches/part_1.csv")

In [8]:
bd.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,516733,2020-12-22 20:30:27,503874407318,fraud_Parker-Kunde,personal_care,1.80,Andrew,Mcgee,M,4130 Tiffany Glen Apt. 562,...,29.5894,-98.5201,1595797,Exhibition designer,1975-12-28,d9ce24d0402de602f672aad6846341ba,1387744227,29.760897,-97.711639,0
1,455518,2019-07-21 04:02:54,675909898057,fraud_Kiehn Inc,grocery_pos,114.66,Christopher,Henry,M,1198 Robert Stravenue Apt. 479,...,41.1360,-73.7009,7987,Television/film/video producer,1964-03-16,f79fb23187ac2e2a5340bc2bd6977b0e,1342843374,40.181098,-74.074658,0
2,24653,2019-01-15 06:58:17,343819048608995,fraud_Kerluke Inc,misc_net,5.66,Shelby,Cannon,F,1535 Ryan Burgs Suite 919,...,41.5855,-93.6719,222785,Wellsite geologist,1956-01-24,f7a8019bf073a0d0d3fe989964f69e4e,1326610697,41.872861,-93.593975,0
3,538193,2019-08-18 22:56:31,2348245054386329,fraud_Lubowitz Terry and Stracke,personal_care,20.22,Justin,Gay,M,268 Hayes Rue Suite 811,...,42.1767,-79.9416,2518,Event organiser,1946-02-02,af21daf61caede2be22a8281914935a5,1345330591,42.280778,-79.163181,0
4,1173680,2020-05-04 22:14:17,30197398657930,fraud_Pfeffer and Sons,shopping_pos,45.08,April,Johnson,F,9727 Deleon Mountain,...,36.1124,-78.6476,12335,Chief Strategy Officer,1987-09-19,a4f11566e429463808a01f1c5738eb85,1367705657,35.959581,-78.434569,0

In [9]:
bd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 23 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Unnamed: 0             1000000 non-null  int64
 1   trans_date_trans_time  1000000 non-null  object
 2   cc_num                 1000000 non-null  int64
 3   merchant               1000000 non-null  object
 4   category               1000000 non-null  object
 5   amt                    1000000 non-null  float64
 6   first                  1000000 non-null  object
 7   last                   1000000 non-null  object
 8   gender                 1000000 non-null  object
 9   street                 1000000 non-null  object
 10  city                   1000000 non-null  object
 11  state                  1000000 non-null  object
 12  zip                    1000000 non-null  int64
 13  lat                    1000000 non-null  float64
 14  long                   1000000 non-null  float64
 15  city_pop               1000000 non-null  int64
 16  job                    1000000 non-null  object
 17  dob                    1000000 non-null  object
 18  trans_num              1000000 non-null  object
 19  unix_time              1000000 non-null  int64
 20  merch_lat              1000000 non-null  float64
 21  merch_long             1000000 non-null  float64
 22  is_fraud               1000000 non-null  int64
dtypes: float64(5), int64(6), object(12)
memory usage: 175.5+ MB

In [12]:
bd.tail(1)

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
999999,306712,2019-05-28 18:50:06,4464457352619,fraud_Bradtke Torp and Bahringer,personal_care,4.03,Breanna,Rodriguez,F,118 Cabrera Springs Apt. 105,...,29.8826,-84.5964,217,Television production assistant,1990-01-24,db7df7f56e8f78f7a41b353e904074a2,1338231006,29.207081,-85.537238,0